//! The Civilization Engine's boundary and save schemas.
//!
//! - [`wire`]: payloads of `commons-wire` frames ([ADR-0001]). The frame kind decides the root
//!   table (see `schema/tce_wire.fbs`).
//! - [`save`]: payloads of `commons-persist` sections ([ADR-0002]).
//!
//! Both are generated by flatc 25.12.19 from `schema/*.fbs` into `src/generated/`. Never edit the
//! generated files; change the schema and run `tools/gen-schema.sh`. CI checks they match.
//!
//! [ADR-0001]: ../../../../decisions/0001-boundary-schema.md
//! [ADR-0002]: ../../../../decisions/0002-snapshot-container.md

#[allow(
    unsafe_code,
    unused_imports,
    dead_code,
    deprecated,
    non_camel_case_types,
    non_snake_case,
    missing_debug_implementations,
    mismatched_lifetime_syntaxes,
    clippy::all,
    clippy::pedantic,
    clippy::unwrap_used
)]
#[rustfmt::skip]
mod wire_generated {
    include!("generated/tce_wire_generated.rs");
}

#[allow(
    unsafe_code,
    unused_imports,
    dead_code,
    deprecated,
    non_camel_case_types,
    non_snake_case,
    missing_debug_implementations,
    mismatched_lifetime_syntaxes,
    clippy::all,
    clippy::pedantic,
    clippy::unwrap_used
)]
#[rustfmt::skip]
mod save_generated {
    include!("generated/tce_save_generated.rs");
}

pub use flatbuffers;
pub use save_generated::tce::save;
pub use wire_generated::tce::wire;

use commons_wire::SchemaId;

/// Major version of the wire schema. Peers with a different major cannot talk.
pub const WIRE_SCHEMA_MAJOR: u16 = 1;
/// Minor version of the wire schema: bumped by additive changes.
pub const WIRE_SCHEMA_MINOR: u16 = 57;
/// The identity carried in every frame header.
pub const WIRE_SCHEMA: SchemaId = SchemaId::new(*b"TCE\0", WIRE_SCHEMA_MAJOR, WIRE_SCHEMA_MINOR);

/// Engine tag in save headers.
pub const SAVE_ENGINE_TAG: [u8; 8] = *b"TCE\0\0\0\0\0";
/// World-state schema version written into save headers. Bump it, and add a migration, whenever a
/// section's meaning changes.
pub const SAVE_SCHEMA_VERSION: u32 = 64;
/// File extension of save generations.
pub const SAVE_EXTENSION: &str = "tcesave";

#[cfg(test)]
mod tests {
    use super::*;
    use flatbuffers::FlatBufferBuilder;

    #[test]
    fn a_command_union_round_trips() {
        let mut fbb = FlatBufferBuilder::new();
        let preset = fbb.create_string("core:worldgen/river_valley");
        let name = fbb.create_string("Test");
        let body = wire::NewWorld::create(
            &mut fbb,
            &wire::NewWorldArgs {
                seed: 42,
                preset_id: Some(preset),
                size_cells: 512,
                name: Some(name),
                band_size: 30,
                regime_id: None,
                neighbours: None,
                neighbours_known: false,
            },
        );
        let command = wire::Command::create(
            &mut fbb,
            &wire::CommandArgs {
                body_type: wire::CommandBody::NewWorld,
                body: Some(body.as_union_value()),
            },
        );
        fbb.finish(command, None);
        let bytes = fbb.finished_data();

        let decoded = flatbuffers::root::<wire::Command>(bytes).expect("verifies");
        let new_world = decoded.body_as_new_world().expect("is NewWorld");
        assert_eq!(new_world.seed(), 42);
        assert_eq!(new_world.size_cells(), 512);
        assert_eq!(new_world.band_size(), 30);
        assert_eq!(new_world.preset_id(), Some("core:worldgen/river_valley"));
    }

    #[test]
    fn garbage_fails_verification() {
        assert!(flatbuffers::root::<wire::Command>(&[1, 2, 3, 4, 5, 6, 7, 8]).is_err());
    }

    #[test]
    fn schema_identity_is_tce() {
        assert_eq!(WIRE_SCHEMA.to_string(), "TCE 1.57");
    }
}
