/* The Civilization Engine's kernel library, `tce_kernel`: its C interface, ABI 1.
 * See decisions/0005-kernel-c-interface.md. Generated by cbindgen from
 * kernel/crates/civ-ffi/src/exports.rs; do not edit. */

#ifndef TCE_KERNEL_H
#define TCE_KERNEL_H

#include <stddef.h>
#include <stdint.h>

// The ABI's major version. A host built for another major must not use this library.
#define TCE_ABI_MAJOR 1

// The ABI's minor version. Minors only append functions to the table and fields to structures.
#define TCE_ABI_MINOR 0

// Done.
#define TCE_OK 0

// Nothing is waiting: no frame to poll, or no snapshot newer than the one asked after.
#define TCE_NONE 1

// The output does not fit; `out_len` holds the size needed and the frame is kept.
#define TCE_BUFFER_TOO_SMALL 2

// A null pointer, a structure smaller than this ABI's, an empty or non-UTF-8 path.
#define TCE_INVALID_ARGUMENT -1

// Not a frame the kernel accepts (see `last_error`); nothing was queued.
#define TCE_BAD_FRAME -2

// The kernel could not start, or the panel server could not (see `last_error`).
#define TCE_FAILED -3

// The kernel failed while running and accepts nothing more; destroy it.
#define TCE_FAULTED -4

// The host wants another ABI major or a larger table than this library has.
#define TCE_INCOMPATIBLE -5

// The engine has stopped.
#define TCE_STOPPED -6

// A running kernel. Opaque: only pointers to it cross the boundary.
typedef struct TceKernel TceKernel;

// The versions this library speaks: of the ABI, and of the schemas and content it carries.
typedef struct TceVersions {
  // `sizeof(TceVersions)` as the host compiled it.
  uint32_t struct_size;
  // `TCE_ABI_MAJOR`.
  uint32_t abi_major;
  // `TCE_ABI_MINOR`.
  uint32_t abi_minor;
  // The boundary schema's major version (ADR-0001).
  uint32_t wire_major;
  // The boundary schema's minor version.
  uint32_t wire_minor;
  // The save schema version (ADR-0002).
  uint32_t save_schema;
  // The content API version content packs must declare.
  uint32_t content_api;
} TceVersions;

// Bytes the caller owns, lent for one call: UTF-8 text for strings and paths, no NUL needed.
typedef struct TceBytes {
  // The first byte; may be null when `len` is 0.
  const uint8_t *ptr;
  // How many bytes.
  size_t len;
} TceBytes;

// What `create` needs.
typedef struct TceConfig {
  // `sizeof(TceConfig)` as the host compiled it.
  uint32_t struct_size;
  // Reserved: 0.
  uint32_t flags;
  // The content folder (the repository's `content/`).
  struct TceBytes content_dir;
  // The saves folder; created when missing.
  struct TceBytes saves_dir;
} TceConfig;

// What `serve_panels` needs.
typedef struct TcePanelConfig {
  // `sizeof(TcePanelConfig)` as the host compiled it.
  uint32_t struct_size;
  // Port on 127.0.0.1; 0 picks a free one.
  uint16_t port;
  // Reserved: 0.
  uint16_t reserved;
  // The built web shell (`web/dist`); empty when there is none.
  struct TceBytes web_dir;
} TcePanelConfig;

// The table of ABI 1 functions `tce_get_api` fills.
typedef struct TceApiV1 {
  // How many bytes of the table this library filled.
  uint32_t struct_size;
  // `TCE_ABI_MAJOR`.
  uint32_t abi_major;
  // `TCE_ABI_MINOR`.
  uint32_t abi_minor;
  // Writes the versions this library speaks into `out` (its `struct_size` set by the host).
  int32_t (*versions)(struct TceVersions *out);
  // Creates a kernel. Writes it to `out` even when it could not start: `create` then returns
  // `TCE_FAILED`, and the kernel must still be destroyed.
  int32_t (*create)(const struct TceConfig *config, struct TceKernel **out);
  // Stops and frees a kernel: the panel server, then the engine (saving a changed world).
  // Blocks. Must not race any other call on the kernel, which must not be used again.
  int32_t (*destroy)(struct TceKernel *kernel);
  // `TCE_OK` while running, `TCE_FAILED` if it never started, `TCE_FAULTED` if it failed.
  int32_t (*status)(const struct TceKernel *kernel);
  // Copies the last failure, UTF-8, into `buf`; its length goes to `out_len`.
  int32_t (*last_error)(const struct TceKernel *kernel, uint8_t *buf, size_t cap, size_t *out_len);
  // Queues one commons-wire frame: a `Command`, `Query` or `Heartbeat`. Copied before return.
  int32_t (*submit)(struct TceKernel *kernel, const uint8_t *frame, size_t len);
  // Copies the next ordered frame (`Welcome`, `Events`, `Response`, `Error`) into `buf`.
  int32_t (*poll)(struct TceKernel *kernel, uint8_t *buf, size_t cap, size_t *out_len);
  // Copies the latest `Snapshot` frame into `buf` if its number is greater than `after`, and
  // its number into `out_number`.
  int32_t (*copy_snapshot)(struct TceKernel *kernel,
                           uint64_t after,
                           uint8_t *buf,
                           size_t cap,
                           size_t *out_len,
                           uint64_t *out_number);
  // Serves the web panels and their socket on 127.0.0.1; `TCE_OK` if already serving.
  int32_t (*serve_panels)(struct TceKernel *kernel, const struct TcePanelConfig *config);
  // Copies the panels' address, with port and token, into `buf`; `TCE_NONE` before
  // `serve_panels`.
  int32_t (*panel_url)(const struct TceKernel *kernel, uint8_t *buf, size_t cap, size_t *out_len);
} TceApiV1;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Fills `out` with the table of ABI 1 functions: the library's only export (ADR-0005 §2).
// Returns `TCE_INCOMPATIBLE`, writing nothing, when `abi_major` is not `TCE_ABI_MAJOR` or
// `out_size` is smaller than this ABI's table.
//
// # Safety
//
// `out` must be null or point to `out_size` writable bytes, aligned for `TceApiV1`.
int32_t tce_get_api(uint32_t abi_major, struct TceApiV1 *out, size_t out_size);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TCE_KERNEL_H */
